// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqCQk0230WxpQ8dp735Gv9Ul8Pw9IUp60',
    appId: '1:757756784372:web:98b94bc13003f4dbf3b8a1',
    messagingSenderId: '757756784372',
    projectId: 'solarstat-c7d5d',
    authDomain: 'solarstat-c7d5d.firebaseapp.com',
    storageBucket: 'solarstat-c7d5d.firebasestorage.app',
    measurementId: 'G-KBCPCQW06Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwoTNPNbbqr6w9Jm2TyDjLOCAUNxso8VI',
    appId: '1:757756784372:android:cb73190fc4851cb4f3b8a1',
    messagingSenderId: '757756784372',
    projectId: 'solarstat-c7d5d',
    storageBucket: 'solarstat-c7d5d.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqCQk0230WxpQ8dp735Gv9Ul8Pw9IUp60',
    appId: '1:757756784372:web:d49eb0b09173369ff3b8a1',
    messagingSenderId: '757756784372',
    projectId: 'solarstat-c7d5d',
    authDomain: 'solarstat-c7d5d.firebaseapp.com',
    storageBucket: 'solarstat-c7d5d.firebasestorage.app',
    measurementId: 'G-NTBC9Y63SC',
  );
}
